### PR TITLE
refactor: optimize ci action config

### PR DESCRIPTION
**Pull request by dengliming**

### CODE REVIEW

**Review by colorful3 — APPROVED** [review]
LGTM

**Review by colorful3 — APPROVED** [review]
LGTM

**Comment by dengliming** [comment]
The ci test failed and it‘ is not related to this PR. Should i fix it this PR or separated PR?

**Comment by colorful3** [comment]
> The ci test failed and it‘ is not related to this PR. Should i fix it in this PR or a separated PR?

You could separate a new PR, Thanks!

**Pull request merged**
